# Generated by Django 4.2.16 on 2024-09-27 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(choices=[('Python Basics', 'Python Basics'), ('Advanced Python', 'Advanced Python'), ('Regular Expressions', 'Regular Expressions'), ('Database/SQL', 'Database/SQL'), ('Django', 'Django'), ('Data Libraries', 'Data Libraries'), ('Mathematics', 'Mathematics'), ('Machine Learning', 'Machine Learning'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('Java script', 'Java script'), ('React JS', 'React JS')], max_length=40)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(80)])),
            ],
        ),
    ]
