# Generated by Django 4.2.16 on 2024-09-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
