# Generated by Django 4.2.16 on 2024-09-27 23:15

import django.core.validators
from django.db import migrations, models
import trainers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=10)),
                ('college', models.CharField(max_length=30)),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)])),
                ('training_exp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(50)])),
                ('email', models.EmailField(max_length=60, validators=[trainers.models.validate_gmail])),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)')], default='+91', max_length=3)),
                ('phone_number', models.CharField(help_text='Enter a valid 10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')])),
            ],
        ),
    ]
