# Generated by Django 4.2.16 on 2024-09-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
