# Generated by Django 4.2.16 on 2024-09-27 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        ('topicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(200)])),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)')], default='+91', max_length=3)),
                ('phone_number', models.CharField(help_text='Enter a valid 10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')])),
                ('fees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(80000)])),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topicapp.topic')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
            ],
        ),
    ]
