# Generated by Django 4.2.16 on 2024-09-27 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email_id', models.EmailField(help_text='This will be your username of your account and also provided access to entire course material in Google Drive during the course.', max_length=60, unique=True)),
                ('country_code', models.CharField(choices=[('+91', 'India (+91)')], default='+91', max_length=3)),
                ('phone_number', models.CharField(help_text='Mobile number will be used to give you updates about registered course over your WhatsApp.', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Mobile number must be exactly 10 digits.')])),
                ('select_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapp.course')),
            ],
        ),
    ]
